#!/usr/bin/sh

##########################################
## FILE: getfile
## DESC: 根据lst配置文件取文件到当前目录,
##       并检查配置文件合法性
## DATE: 2014-07-04
## AUTH: WangYunQi
##########################################

# 检查输入参数是否合法
if [ $# -lt 1 ]
then
	echo	"\n\n\tUsage: $0 + 问题单号\n\n"
	exit
fi

# 检查lst配置文件是否存在
lst_file=$1.lst
if [ ! -f "$lst_file" ]
then
	echo	"lst配置文件[$lst_file]不存在!"
	exit
fi

echo	"\n\n=== 配置文件[$lst_file]处理开始 ===\n\n"

# 遍历配置文件
while read line
do
	num=`echo $line | awk -F'|' '{print NF}'`
	if [ $num -ne 2 ]
	then
		echo	"配置非法[$line]"
	else
		Dir=`echo $line | awk -F'|' '{print $1}'`
		File=`echo $line | awk -F'|' '{print $2}'`

		if [ "#" = $Dir ]
		then
			if [ ! -f "$File" ] ; then
				echo	"文件[$File]不存在! 配置[$line]"
			fi
		else
			if [ ! -f "$HOME/$Dir/$File" ] ; then
				echo	"文件[$File]不存在! 配置[$line]"
			else
				if [ -f "$File" ]
				then
					nn=`diff $File $HOME/$Dir/$File`

					if [ -z "$nn" ]
					then
						echo	"\t文件[$File]无变!"
						continue
					else
						echo    "\n  Old -- [`ls -l $File`]"
						echo    "  New -- [`ls -l $HOME/$Dir/$File`]\n"
					fi
				fi

				cp $HOME/$Dir/$File .
			fi
		fi
	fi
done < $lst_file

echo	"\n\n=== 配置文件[$lst_file]处理完成 ===\n\n"