language: python
python:
  - "2.7"
# command to install dependencies,
# e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:
 - pyflakes bypy.py
 - pyflakes setup.py
 - pyflakes bypygui.pyw
 - python setup.py test
 - python -m doctest -v bypy.py
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
